CREATE TABLE user(
    id int(11) unsigned NOT NULL AUTO_INCREMENT,
    first_name VARCHAR(100) NOT NULL DEFAULT '',
    last_name VARCHAR(100) NOT NULL DEFAULT '',
    email VARCHAR(100) NOT NULL DEFAULT '',
    age int(3) NOT NULL DEFAULT 0,
    address VARCHAR(100) NOT NULL DEFAULT '',
    status VARCHAR(20) NOT NULL DEFAULT 'NOT_REGISTERED',
    join_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    verification int(6) NOT NULL,
    PRIMARY KEY (id)
);